apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storage-hasan
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

