apiVersion: v1
kind: Service
metadata:
  name: my-sql-service
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    #protocol: TCP
      #targetPort: 3306
      #  type: NodePort

